Region.create(name: "North America", countries: "United States, Canada, Mexico, Greenland, Cuba, Domincan Republic, Puerto Rico, Jamaica, The Bahamas, Haiti, Aruba, Bermuda, Barbados, Turks and Caicos Islands, Martinique, Cayman Islands, Grenada, Dominica, Saint Barthélemy, British Virgin Islands, Guadeloupe, U.S. Virgin Islands, Antigua and Barbdua, Anguilla, Saint Kitts and Nevis, Sint Maarten, Saint Pierre and Miquelon, Montserrat, Saint Martin, United States Minour Outlying Islands", description: "North America is a continent entirely within the Northern Hempisphere and almost all within the Western Hempisphere. It's bordered to the north by the Artic Ocean, to the east by the Atlantic Ocean, to the west and south by the Pacific Ocean, and to the southeast by South America and the Caribbean Sea.", animals: "Bison, Bald Eagle"),

Region.create(name: "South America", countries: "Brazil, Argentina, Peru, Colombia, Chile, Venezuela, Bolivia, Ecuador, Uruguay, Paraguay, Guyana, Suriname, French Guiana, Curaçao, Trinidad and Tobago, Falkland Islands(Islas Malvinas), Caribbean Netherlands" , description: "South America is a ocntinent in the Western Hempisphere, mostly in the Southern Hempisphere, with a relatively small portion in the Northern Hempisphere. It's bordered on the west by the Pacific Ocean and on the north and east by the Atlantic Ocean.", animals: "Capybara, LLama" ),

Region.create(name: "Central America", countries: "Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua, Panama", description: "Central America is a region found in the southern tip of North America and is sometimes defined as a subcontinent of the Americas. This region is bordered by Mexico to the north, Columbia to the southeast, the Caribbean sea to the east and the Pacific Ocean to the west and south.", animals: "Ocelot, Jaguarundi"),

Region.create(name: "Africa", countries: "South Africa, Nigeria, Morocco, Kenya, Ghana, Ethiopia, Algeria, Tanzania, Democratic Republic of the Congo, Sudan, Senegal, Uganda, Cameroon, Tunisia, Mali, Zimbabwe, Madagascar, Côte d'Ivoire(Ivory Cost), Angola, Namibia, Zambia, Rwanda, Libya, Mauritius, Mozambique, Somalia, Botswana, Benin, Cape Verde, Guinea, Seychelles, Burkina Faso, Malawi, Niger, Togo, Central AFrican Republic, Liberia, Chad, Eritrea, Gabon, Mauritania, The Gambia, Sierra Leone, Eswatini, Djibouti, Burundi, South Sudan, Réunion, Equatorial Guinea, Lesotho, Republic of the Congo", description: "Afria is the world's second largest and second most-populous continent. It covers 6% of Earth's total surface area and 20% of it's land area. The continent is surrounded by the Mediterranean Sea to the north, the Isthmus of Suez and the Red Sea to the northeast, the Indian Ocean to the southeast and the Atlantic Ocean to the west.", animals: "White rhinoceros, Western green mamba"),

Region.create(name: "Asia", countries: "India, Japan, China, Indonesia, Vietnam, Thailand, Singapore, South Korea, Hong Kong, Philippines, Malaysia, Myanmar(Burma), Cambodia, Bangladesh, Taiwan, Sri Lanka, Malidives, Laos, Nepal, North Korea, Brunei, Mongolia, Macao, Bhutan, Bahrain, Timor-Leste, Christmas Island, Cocos(Keeling) Islands", description: "Asia is Earth's largest and most populous continent, located primarily in the Eastern and Northern Hempispheres. In general terms, Asia is bounded on the east by the Pacific Ocean, on the south by the Indian Ocean, and on the north by the Artctic Ocean. Theborder of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them.", animals: "Proboscis monkey, Sun bear"),

Region.create(name: "Eastern Europe", countries: "Russia, Belarus, Georgia, Azerbaijan, Kazakhstan, Armenia, Ukraine" , description: "Eastern Europe is the eastern part of the European continent. There is no consistent definition of the precise area it covers, partly because the term has a wide reange of geopolitical, geographical, cultural, and socioeconomic connotations.", animals: "Artic fox, Raccoon dog" ),

Region.create(name: "Middle East", countries: "Iran, Israel, Turkey, Saudi Arabia, Egypt, United Arab Emirates, Syria, Iraq, Lebanon, Qatar, Jordan, Palestine, Kuwait, Bahrain, Yemen, Oman, Cyprus", description: "The Middle East is atranscontinental region centered on Western Asia, Turkey, and Egypt. The Middle East generally has a hot, arid climate, with several major rivers providing irrigation to support agriculture in limited areas such as the Nile Delta in Egypt, the Tigris and Euphrates watersheds of Mesopotamia, and most of what is known as the Fertile Cresent.", animals: "Arabian oryx, Sand cat"),

Region.create(name: "Oceania", countries: "Australia, New Zealand, Indonesia, Fiji, Papua New Guinea, Samoa, Vanatu, Palau, French Polynesia, New Caledonia, Federated States of Micronesia, Tonga, Solomon Islands, Guam, Kiribati, Nauru, Marshall Islands, Tuvalu, Cook Islands, American Samoa, Niue, Pitcairn Islands, Wallis and Futuna, Northern Mariana Islands, Tokelau, Norfolk Island", description: "Oceania spans the eastern and western hempispheres. Definitions of Oceania vary; however, the islands at the geographic extremes of Oceania are generally considered to by the Bonin Islands, a politically integrap part of Japan; Hawaii, a state of the United States; Clipperton Island, a possession of France; the Juan Fernández Islands, belonging to Chile; and Macquarie Island, belonging to Australia.", animals: "Kiwi, Saltwater crocodile"),

Region.create(name: "Caribbean", countries: "The Bahamas, Trinidad and Tobago, Jamaica, Saint Lucia, Dominican Republic, Haiti, Barbados, Grenada, Saint Kitts and Nevis, Dominica, Antigua and Barbuda, Cuba, Saint Vincent and the Grenadines, Cayman Islands, U.S. Virgin Islands, Turks and Caicos Islands, British Virgin Islands, ", description: "The Caribbean is a region of the Americas that consistss of the Caribbean Sea, its islands (some surrounded by the Caribbean Sea and smoe bordering both the Caribbean Sea and the North Atlantic Ocea) and the surrounding coasts.The region is southeast of the Gulf of Mexico and the North American mainland, east of Central America, and north of South America.", animals: "Green iguana, West Indian manatee")

# Animal.create(name: , sciName: , description: , region_id: , country: ,)
