Region.create(name: "North America", countries: "United States, Canada, Mexico, Greenland, Cuba, Domincan Republic, Puerto Rico, Jamaica, The Bahamas, Haiti, Aruba, Bermuda, Barbados, Turks and Caicos Islands, Martinique, Cayman Islands, Grenada, Dominica, Saint Barthélemy, British Virgin Islands, Guadeloupe, U.S. Virgin Islands, Antigua and Barbdua, Anguilla, Saint Kitts and Nevis, Sint Maarten, Saint Pierre and Miquelon, Montserrat, Saint Martin, United States Minour Outlying Islands", description: "North America is a continent entirely within the Northern Hempisphere and almost all within the Western Hempisphere. It's bordered to the north by the Artic Ocean, to the east by the Atlantic Ocean, to the west and south by the Pacific Ocean, and to the southeast by South America and the Caribbean Sea.")

Region.create(name: "South America", countries: "Brazil, Argentina, Peru, Colombia, Chile, Venezuela, Bolivia, Ecuador, Uruguay, Paraguay, Guyana, Suriname, French Guiana, Curaçao, Trinidad and Tobago, Falkland Islands(Islas Malvinas), Caribbean Netherlands" , description: "South America is a ocntinent in the Western Hempisphere, mostly in the Southern Hempisphere, with a relatively small portion in the Northern Hempisphere. It's bordered on the west by the Pacific Ocean and on the north and east by the Atlantic Ocean.")

Region.create(name: "Central America", countries: "Belize, Costa Rica, El Salvador, Guatemala, Honduras, Nicaragua, Panama", description: "Central America is a region found in the southern tip of North America and is sometimes defined as a subcontinent of the Americas. This region is bordered by Mexico to the north, Columbia to the southeast, the Caribbean sea to the east and the Pacific Ocean to the west and south.")

Region.create(name: "Africa", countries: "South Africa, Nigeria, Morocco, Kenya, Ghana, Ethiopia, Algeria, Tanzania, Democratic Republic of the Congo, Sudan, Senegal, Uganda, Cameroon, Tunisia, Mali, Zimbabwe, Madagascar, Côte d'Ivoire(Ivory Cost), Angola, Namibia, Zambia, Rwanda, Libya, Mauritius, Mozambique, Somalia, Botswana, Benin, Cape Verde, Guinea, Seychelles, Burkina Faso, Malawi, Niger, Togo, Central AFrican Republic, Liberia, Chad, Eritrea, Gabon, Mauritania, The Gambia, Sierra Leone, Eswatini, Djibouti, Burundi, South Sudan, Réunion, Equatorial Guinea, Lesotho, Republic of the Congo", description: "Afria is the world's second largest and second most-populous continent. It covers 6% of Earth's total surface area and 20% of it's land area. The continent is surrounded by the Mediterranean Sea to the north, the Isthmus of Suez and the Red Sea to the northeast, the Indian Ocean to the southeast and the Atlantic Ocean to the west.")

Region.create(name: "Asia", countries: "India, Japan, China, Indonesia, Vietnam, Thailand, Singapore, South Korea, Hong Kong, Philippines, Malaysia, Myanmar(Burma), Cambodia, Bangladesh, Taiwan, Sri Lanka, Malidives, Laos, Nepal, North Korea, Brunei, Mongolia, Macao, Bhutan, Bahrain, Timor-Leste, Christmas Island, Cocos(Keeling) Islands", description: "Asia is Earth's largest and most populous continent, located primarily in the Eastern and Northern Hempispheres. In general terms, Asia is bounded on the east by the Pacific Ocean, on the south by the Indian Ocean, and on the north by the Artctic Ocean. Theborder of Asia with Europe is a historical and cultural construct, as there is no clear physical and geographical separation between them.")

Region.create(name: "Eastern Europe", countries: "Russia, Belarus, Georgia, Azerbaijan, Kazakhstan, Armenia, Ukraine" , description: "Eastern Europe is the eastern part of the European continent. There is no consistent definition of the precise area it covers, partly because the term has a wide reange of geopolitical, geographical, cultural, and socioeconomic connotations.")

Region.create(name: "Middle East", countries: "Iran, Israel, Turkey, Saudi Arabia, Egypt, United Arab Emirates, Syria, Iraq, Lebanon, Qatar, Jordan, Palestine, Kuwait, Bahrain, Yemen, Oman, Cyprus", description: "The Middle East is atranscontinental region centered on Western Asia, Turkey, and Egypt. The Middle East generally has a hot, arid climate, with several major rivers providing irrigation to support agriculture in limited areas such as the Nile Delta in Egypt, the Tigris and Euphrates watersheds of Mesopotamia, and most of what is known as the Fertile Cresent.")

Region.create(name: "Oceania", countries: "Australia, New Zealand, Indonesia, Fiji, Papua New Guinea, Samoa, Vanatu, Palau, French Polynesia, New Caledonia, Federated States of Micronesia, Tonga, Solomon Islands, Guam, Kiribati, Nauru, Marshall Islands, Tuvalu, Cook Islands, American Samoa, Niue, Pitcairn Islands, Wallis and Futuna, Northern Mariana Islands, Tokelau, Norfolk Island", description: "Oceania spans the eastern and western hempispheres. Definitions of Oceania vary; however, the islands at the geographic extremes of Oceania are generally considered to by the Bonin Islands, a politically integrap part of Japan; Hawaii, a state of the United States; Clipperton Island, a possession of France; the Juan Fernández Islands, belonging to Chile; and Macquarie Island, belonging to Australia.")

Region.create(name: "Caribbean", countries: "The Bahamas, Trinidad and Tobago, Jamaica, Saint Lucia, Dominican Republic, Haiti, Barbados, Grenada, Saint Kitts and Nevis, Dominica, Antigua and Barbuda, Cuba, Saint Vincent and the Grenadines, Cayman Islands, U.S. Virgin Islands, Turks and Caicos Islands, British Virgin Islands, ", description: "The Caribbean is a region of the Americas that consistss of the Caribbean Sea, its islands (some surrounded by the Caribbean Sea and smoe bordering both the Caribbean Sea and the North Atlantic Ocea) and the surrounding coasts.The region is southeast of the Gulf of Mexico and the North American mainland, east of Central America, and north of South America.")

Animal.create(name: "American Bison", sciName: "Bison bison", animalClass: "Mammal", description: 'The American bison or simply bison, also commonly known as the American buffalo or buffalo, is a North American species of bison that once raomed North America in vast herds. They became nearly extinct by a combination of commercial hunting and slaughter in the 19th century and the introduction of bovine diseases from domestic cattle. Recovery efforts expanded in the mid-20th century, with a resurgence to roughly 31,000 animals today, largely restricted to a few national parks and reserves.', region_id: 1, country: "North America", image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.jpg")

Animal.create(name: "Bald Eagle", sciName: "Haliaeetus leucocephalus", animalClass: "Bird", description: "The bald eagle is a bird of prey found in North America. It's an opportunistic feeder which subsists mainly on fish, which it swoops down and snatches from the water with its talons. It builds the largest nest of any North American bird and the largest tree nests ever recorded for any animal species, u to 13 ft deep and 8.2 ft wide.", region_id: 1, country: "North America", image:"https://www.mtdemocrat.com/files/2019/01/a3-eagle-RGB.jpg")

Animal.create(name: "Carolina Anole", sciName: "Anolis carolinensis", description: "The Carolina anole is an arboreal anole lizard native to the southeastern United States. Other common names include the green anole, American green anole, American anole, and red-throated anole. It is also sometimes referred to as the American chameleon due to its ability to change color from several brown hues to bright green, and its somewhat similar appearance and diet preferences. However it is not a true chameleon and the nickname is misleading although it can camouflage.", region_id: 1, country: "United States", animalClass: "Reptile", image: "http://rivista-cdn.reptilesmagazine.com/images/cache/cache_7/cache_a/cache_9/green-anole2-122589a7.jpeg?ver=1542817071&aspectratio=1.5094339622642")

Animal.create(name: 'White Perch", sciName: "Morone americana", description: "The white perch is not a true perch but is, rather, a fish of the temperate bass family, Moronidae, notable as a food and game fish in eastern North America. In some locales it is referred to incorrectly as "silver bass".Generally silvery-white in color, hence the name, depending upon habitat and size specimens have begun to develop a darker shade near the dorsal fin and along the top of the fish. This sometimes earns them the nickname "black-back". Although favoring brackish waters, it is also found in fresh water and coastal areas from the St. Lawrence River and Lake Ontario south to the Pee Dee River in South Carolina, and as far east as Nova Scotia. They are also found in the lower Great Lakes, Finger Lakes, Long Island Sound and nearby coastal areas, Hudson and Mohawk River system, Delaware Bay and Chesapeake Bay. It is also found occasionally in small land-locked lakes and ponds. The raw meat is of a somewhat pinkish hue, but when cooked, it is white and flaky.', region_id: 1, country: "United States, Canada", animalClass: "Fish", image: "https://farm6.staticflickr.com/5027/5662767908_2257db4017_b.jpg")

Animal.create(name: "Duellmanohyla", sciName: "Duellmanohyla", description: 'Duellmanohyla is a genus of frogs in the family Hylidae found in Oaxaca, Mexico, as well as Central America. These are small stream-breeding frogs have bright red, bronze or yellow irises. Their dorsa are uniform pale green, olive, red-brown or lichenose, with green or olive spots on a black background. Several species have pale upper labial and lateral stripes. Some fingers or toes have moderate webbing.', region_id: 1, country: "Mexico, Central America", animalClass: "Amphibian", image: "https://s2r.iucnredlist.org/sis2_images/2042732767.jpg")

Animal.create(name: "Capybara", sciName: "Hydrochoerus hydrochaeris", description: "The capybara is a mammal native to South America. It's the largest living rodent in the world. Its close relatives include guinea pigs and rock cavies, and it's more distantly related to the agouti, the chinchilla, and the coypu. The caybara inhabits savannas and dense forests and lives near bodies of water. It's a highly social species and can be found in groups as large as 100 individuals, but usually lives in group of 10-20 individuals. The capybara is not a threatened species but it is hunted for its meat, hide, and grease from its thick fatty skin, which is used in the pharmaceutical trade.", region_id: 2, country: "South America", animalClass: "Mammal", image: "https://www.nationalgeographic.com/content/dam/animals/thumbs/rights-exempt/mammals/c/capybara.jpg")

Animal.create(name: "Red-Bellied Piranha", sciName: "Pygocentrus nattereri", description: "The red-bellied piranha, also known as the red piranha, is a species of piranha native to South America, found in the Amazon, Paraguay, Paraná and Essequibo basins, as well as coastal rivers of northeastern Brazil. They are omnivorous foragers and feed on insects, worms, crustaceans and fish. They are not a migratory species, but do travel to seek out conditions conducive to breeding and spawning during periods of increased rainfall. Red-bellied piranhas often travel in shoals as a predatory defense, but rarely exhibit group hunting behavior. Acoustic communication is common, and is sometimes exhibited along with aggressive behaviors. Through media influence, the red-bellied piranha has developed a reputation as a ferocious predator, though this is not actually the case. They are a popular aquarium fish.", region_id: 2, country: "Brazil", animalClass: "Fish", image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Gregory_Moine_-_Red_bellied_Piranha_%28by%29.jpg")

Animal.create(name: "Black Caiman", sciName: "Melanosuchus niger", description: "The black caiman is the largest predator in the Amazon ecosystem, preying on a variety of fish, reptiles, birds, and mammals. It is a generalist and apex predator, potentially capable of taking any animal within its range, including other predators. Few ecological studies have been carried out on the species, but the black caiman has its own ecological niche that enables coexistence without too much competition. As the largest predator in the ecosystem, it may also be a keystone species, playing an important role of maintaining the structure of the ecosystem. Once common, it was hunted to near extinction primarily for its commercially valuable hide. It is now making a comeback, listed as Conservation Dependent.", region_id: 2, country: "South America", animalClass: "Reptile", image: "https://i.ytimg.com/vi/h0eM5IqUO-0/maxresdefault.jpg")

Animal.create(name: "Bat Falcon", sciName: "Falco rufigularis", description: "This small dark bird of prey inhabits open woodlands and forest clearings. Bat falcons perch conspicuously on high, open snags, from which they launch aerial attacks on their prey. They hunt bats, birds, and large insects such as dragonflies. The smaller male takes more insects, and the female more birds and bats. The flight is direct and powerful. This falcon is partly crepuscular, as the bats in its diet suggest. It lays two or three brown eggs in an unlined treehole nest. It was long known as Falco albigularis; the names Falco fusco-coerulescens or Falco fuscocaerulescens, long used for the aplomado falcon, are now believed to refer to the present species.", region_id: 2, country: "Mexico, Central America, South America, Trinidad", animalClass: "Bird", image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/OFalco_rufigularis_Bat_Falcon.jpg")

Animal.create(name: "Ameerega hahneli", sciName: "Ameerega hahneli", description: "The back and limbs are finely granular and brown in colour, with or without black spots. The flanks are black and bordered above by a narrow, white or cream coloured dorsolateral line that extends from the tip of the snout to the groin. There is also a white or cream coloured labial stripe that does not extend onto the arm. The venter is blue with black reticulations. There are yellow-orange oval spots on the ventral surfaces of the arms, inner surfaces of the shanks, and in the groin. The iris is dark brown.", region_id: 2, country: "Brazil, Bolivia, Peru, Ecuador, Columbia, Venezuela, Guyana, French Guiana, Suriname", animalClass: "Amphibian", image: "http://www.understoryenterprises.com/wp-content/themes/understory/images/landing/ameerega-hahneli.jpg")

Animal.create(name: "Ocelot", sciName: "Leopardus pardalis", description: "The ocelot is a small wild cat native to the southwestern United States, Mexico, Central and South America. It's listed as a Least Concern on the IUCN Red List as the population is estimated to comprise more than 40,000 mature individuals and is considered stable. Its fur was once regarded as valuable, and poaching for the illegal trade is still a threat. Ocelots are marked with solid black spots, streaks and stripes.", region_id: 3, country: "Central America", animalClass: "Mammal", image: "https://pantherridge.org/wp-content/uploads/2013/03/DSC_9488_tn.jpg")

Animal.create(name: "Strawberry Poison-Dart Frog", sciName: "Oophaga pumilio", description: "The strawberry poison frog or strawberry poison-dart frog is a species of small poison dart frog found in Central America. It's common throughout its range, which extends from eastern central Nicaragua through Costa Rica and northwestern Panama. The strawberry poison frog is perhaps most famous for its widespread variation in coloration, comprising approximately 15-30 color morphs, most of which are presumed to be true-breeding.", region_id: 3, country: "Central America", animalClass: "Amphibian", image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Oophaga_pumilio_%28Strawberry_poision_frog%29_%282532163201%29.jpg")

Animal.create(name: "White-Lipped Mud Turtle", sciName: "Kinosternon leucostomum", description: "The white-lipped mud turtle is a species of mud turtle in the family Kinosternidae. The species is endemic to Central America and northwestern South America.", region_id: 3, country: "Central America, South America", animalClass: "Reptile", image: "https://www.reptilefact.com/wp-content/uploads/2017/04/White-Lipped-Mud-Turtle-Images.jpg")

Animal.create(name: "Roosterfish", sciName: "Nematistius pectoralis", description: 'The roosterfish is a game fish found in the warmer waters of the East Pacific from Baja California to Peru. It is the only species in the genus Nematistius and the family Nematistiidae. It is distinguished by its "rooster comb", seven very long spines of the dorsal fin. The roosterfish has an unusual arrangement of its ears: the swim bladder penetrates the brain through the large foramina and makes contact with the inner ear. It uses its swim bladder to amplify sounds.', region_id: 3, country: "United States, Peru", animalClass: "Fish", image: "https://www.crocodilebay.com/wp-content/uploads/2018/06/Rooster_underwater.jpg")

Animal.create(name: "Resplendent Quetzal", sciName: "Pharomachrus mocinno", description: 'The resplendent quetzal was first described by Mexican naturalist Pablo de La Llave in 1832. It is one of five species of the genus Pharomachrus known as quetzals. The term "quetzal" was originally used for just this species, but is now applied to all members of the genera Pharomachrus and Euptilotis. The word "quetzal" came from Nahuatl (Aztec), where quetzalli (from the root quetza = "stand") meant "tall upstanding plume" and then "quetzal tail feather"; from that Nahuatl quetzaltotōtl means "quetzal-feather bird" and thus "quetzal".', region_id: 3, country: "Mexico, Panama", animalClass: "Bird", image: "https://www.hbw.com/sites/default/files/styles/ibc_1k/public/ibc/p/_50c7958.jpg?itok=uKrShy7C")

Animal.create(name: "White Rhinoceros", sciName: "Ceratotherium simum", description: "The white rhinoceros or square-lipped rhinoceros is the largest extant species of rhinoceros. It has a wide mouth used for grazing and is the most social of all rhino species. The white rhino consists of two subspecies: the southern white rhinoceros and the much rarer northern white rhinoceros. The northern subspecies has very few remaining with only two confirmed left in 2018.", region_id: 4, country: "South Africa, Namibia, Zimbabwe, Kenya, Uganda", animalClass: "Mammal", image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Waterberg_Nashorn3.jpg")

Animal.create(name: "Wildebeest", sciName: "", description: "The wildebeest, also called the gnu, is an antelope in the genus Connochaetes. It belongs to the family Bovidae, which includes antelopes, cattle, goats, sheep, and other even-toes horned ungulates. Connochaetes includes two species, both native to Africa: the black wildebeest or white-tailed gnu, and the blue wildebeest or brindled gnu. The most obvious way of telling the two species apart are the differences in their coloring and in the way their horns are oriented.", region_id: 4, country: "Kenya, Tanzania, Botswana, Zimbabwe, Mozambique, South Africa, Eswatini", animalClass: "Mammal", image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Blue_Wildebeest%2C_Ngorongoro.jpg")

Animal.create(name: "Dwarf Crocodile", sciName: "Osteolaemus tetraspis", description: "The dwarf crocodile, also known commonly as the African dwarf crocodile, broad-snouted crocodile, or bony crocodile, is an African crocodile that is also the smallest extant crocodile species. Sampling has identified three genetically distinct populations. Some feel that the findings should elevate the subspecies to full species status.", region_id: 4, country: "Democratic Republic of Congo.", animalClass: "Reptile", image: "https://kids.sandiegozoo.org/sites/default/files/2017-12/animal-hero-dwarf-croc.jpg")

Animal.create(name: "Reedfish", sciName: "Erpetoichthys calabaricus", description: "The reedfish, ropefish (more commonly used in the United States), or snakefish, is a species of freshwater fish in the bichir family and order. It is the only member of the genus Erpetoichthys. It is native to West and Central Africa. The reedfish possesses a pair of lungs in addition to gills, allowing it to survive in very oxygen-poor water. It is threatened by habitat loss through palm oil plantations, other agriculture, deforestation, and urban development.", region_id: 4, country: "West and Central Africa", animalClass: "Fish", image: "https://www.azgardens.com/wp-content/uploads/2017/05/Ropefish-Erpetoichthys-calabaricus.jpg")

Animal.create(name: "African Oystercatcher", sciName: "Haematopus moquini", description: "The African oystercatcher or African black oystercatcher is a large charismatic wader resident to the mainland coasts and offshore islands of southern Africa. This near-threatened oystercatcher has a population of over 6,000 adults, which breed between November and April. The African oystercatcher is a large, noisy wader, with completely black plumage, red legs and a strong broad red bill. The sexes are similar in appearance, however, females are larger and have a slightly longer beak than males. Juveniles have soft grey plumage and do not express the characteristic red legs and beak until after they fledged. The call is a distinctive loud piping, very similar to Eurasian oystercatchers. As the Eurasian oystercatcher is a migratory species they only occur as a vagrant in southern Africa, and its black-and-white plumage makes confusion impossible.", region_id: 4, country: "Angola, Mozambique, Nambia, Mazeppa Bay", animalClass: "Bird", image: "https://upload.wikimedia.org/wikipedia/commons/e/ed/African_Black_Oystercatcher_%282%29.JPG")

Animal.create(name: "Arum Frog", sciName: "Hyperolius horstockii", description: "They have bright orange feet and can change their colour to camouflage themselves. The top of the body is cream to brown, sometimes with small black spots. A distinctive, pale, dorsolateral line runs from the snout along the flanks, with a dark-brown lateral band underneath. A fine, dark line usually separates the pale line from the brown band. The concealed surfaces of limbs, webbing, and discs are orange to red. Underneath, the frog is creamy white and slightly granular. The gular flap in males is bright ochre. their pupils are horizontal.", region_id: 4, country: "South Africa", animalClass: "Amphibian", image: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Hyperolius_horstockii.jpg")

Animal.create(name: "Gharial", sciName: "Gavialis gangeticus", description: "The gharial, also known as the gavial, and the fish-eating crocodile is a crocodilian in the family Gavialidae, native to sandy freshwater river banks in the plains of the northern part of the Indian subcontinent. It's threatened by loss of riverine habitat, depletion of fish resources, and entaglement in fishing nets. The gharial is listed as Critically Endangered on the IUCN Red List. Today, its distribution is limited to only 2% of its historical range. It's one of the longest of all living crocodilians, with males reaching a body length up to 20 ft.", region_id: 5, country: "India, Nepal", animalClass: "Reptile", image: "https://i.ytimg.com/vi/E0yF-vcaOKA/maxresdefault.jpg")

Animal.create(name: "Golden Mandarin Fish", sciName: "Siniperca scherzeri", description: "The golden mandarin fish, also known as the leopard mandarin fish, is a species of temperate perch native to eastern Asia. This species can reach at least 1.1 ft in standard length and 1.34 lb in weight. It's typically a yellowish-brown with blackis-brown speckles ('leopard'), but there are also birght yello ('golden') individuals, which are particularly prized in Korea and selectively breed in captivity.", region_id: 5, country: "Korea, China, Vietnam", animalClass: "Fish", image: "https://alchetron.com/cdn/golden-mandarin-fish-ba7a8abc-12e0-4a47-8402-d95007ecfb5-resize-750.jpeg")

Animal.create(name: "Indian Scops Owl", sciName: "Otus bakkamoena", description: "The Indian scops owl is a small (23–25 cm) owl, although it is one of the largest of the scops owls. Like other scops owls, it has small head tufts, or ears. The upperparts are grey or brown, depending on the morph, with faint buff spotting. The underparts are buff with fine darker streaking. The facial disc is whitish or buff, and the eyes are orange or brown. There is a buff neckband. Sexes are similar.", region_id: 5, country: "Southeast Asia, Indonesia", animalClass: "Bird", image: "http://www.mangoverde.com/birdsound/images/00000009787.jpg")

Animal.create(name: "Afghan Hedgehog", sciName: "Hemiechinus auritus megalotis", description: "The Afghan hedgehog is a subspecies of the long-eared hedgehog native to Afghanistan and western Pakistan. It is larger and reddish in colour, but otherwise similar in appearance to the long-eared hedgehog. Since the Afghan hedgehog occupies mostly mountainous areas, are abundant at 1000 meters, and often found as high as 2500 meters, thus living at the highest elevation among hedgehog species, lower temperatures probably made it evolve larger. It also hibernates for approximately six months. Another adaptation for mountain terrain that this subspecies possesses long claws on its legs, which are more suitable for climbing.", region_id: 5, country: "Afghanistan, Pakistan", animalClass: "Mammal", image: "https://i.imgur.com/0lm5HKK.jpg")

Animal.create(name: "Anderson's Crocodile Newt", sciName: "Echinotriton andersoni", description: "Anderson's Crocodile Newt is a stout, flat salamander. Head is broad and triangular in shape. There are 12–15 conspicuous knob-like lateral glands. Colouration is uniformly dark brown or black, only the underside of the tail, cloacal region, and the soles of the feet are yellow-orange. The maximum size is at least 80 mm (3.1 in) in snout–vent length and 169 mm (6.7 in) in total length.", region_id: 5, country: "Japan, Taiwan", animalClass: "Amphibian", image: "http://www.naturalhistoryonthenet.com/wp-content/uploads/2017/03/Andersons-Crocodile-Newt.jpg")


Animal.create(name: "Raccoon Dog", sciName: "Nyctereutes procyonoides", description: "The raccoon dog is also known as the mangut, tanuki, or neoguri. It's unrelated to raccoons, and it is a close relative of true foxes rather than the domestic dog. The raccoon dog is named for its superficial resemblance to the raccoon. In Japan, it is known as the tanuki, and has a long history in folklore. In Sweden, where it's called mårdhun, it has been treated as a potentially hazadous invasive species.", region_id: 6, country: "Eastern Europe, Asia", animalClass: "Mammal", image: "https://ichef.bbci.co.uk/news/624/cpsprodpb/D6A4/production/_107184945_racdog.jpg")

Animal.create(name: "Mediterranean Monk Seal", sciName: "Monachus monachus", description: "The Mediterranean monk seal is a monk seal belonging to the family Phocidae. As of 2015, it's estimated that fewer than 700 individuals survive in three or four isolated subpopulations in the Mediterranean, in the Aegean Sea, the archipelago of Madeira and the Cabo Blanco area in the northeastern Atlantic Ocean. It's believed to be the world's rarest pinniped species.", region_id: 6, country: "Eastern Europe, Asia", animalClass: "Mammal", image: "https://www.mmc.gov/wp-content/uploads/HIMonkSeal.jpg")

Animal.create(name: "Sand Lizard", sciName: "Lacerta agilis", description: "The sand lizard is a lacertid lizard distributed across most of Europe and eastwards towards Mongolia. The sand lizard is a sexually dimorphic legged lizard. In northwest Eurpe, both sexes are characterized by lateral and dorsal strips of ocellated (eye-shaped) markings, dark patches with pale centers. They bask on rocks in the day and at night they go into their holes underground. To protect themselves, they pop off their tails and bite the predators.", region_id: 6, country: "Poland, Czech Republic", animalClass: "Reptile", image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Jaszczurka.jpg")

Animal.create(name: "European Goldfinch", sciName: "Carduelis carduelis", description: "The European goldfinch or goldfinch, is a small passerine bird in the finch family that is native to Europe, North Africa and western Asia. It has been introduced to other areas including Australia, New Zealand and Uruguay. The breeding male has a red face and a black-and-white head. The back and flanks are buff or chestnut brown. The black wings have a broad yellow bar. The tail is black and the rump is white. Males and females are very similary, but femails have a slightly smaller red areas on the face. The goldfinch is often depicted in Italian renaissance paintings of the Madonna and Child.", region_id: 6, country: "Europe, North Africa, western Asia, New Zealand, Australia, Uruguay", animalClass: "Bird", image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Carduelis_carduelis_close_up.jpg")

Animal.create(name: "Olm", sciName: "Proteus anguinus", description: "The olm or proteus is an aquatic salamander in the family Proteidae, the only exclusively cave-dwelling chordate species found in Europe. In contrast to most amphibians, it is entirely aquatic; it eats, sleeps, and breeds underwater. This cave slamander is most notable for its adaptations to a life of complete darkness in its underground habitat. The olm's eyes are underdeveloped, leaving it blid, while its other senses, particularly those of smell and hearing, are acutely developed. It lacks any pigmentation in its skin, has three toes on its forelimbs, but only two toes on its hind feet.", region_id: 6, country: "Slovenia, Italy, Croatia, Bosnia, Herzegovina", animalClass: "Amphibian", image: "http://gotrebinje.com/wp-content/uploads/2017/08/Trebinje-Proteus-anguinus-11.09.09-1-693x520.jpg")

Animal.create(name: "Cottus Petiti", sciName: "Cottus petiti", description: "Cottus petiti, also called the chabot du Lez in French, is a species of freshwater sculpin, a fish in the family Cottidae. It's endemic to France, found only in a small 3 km stretch of the Lez River in Southern France near Montpellier. The natural habitat is fed by karstic springs which may have enabled the isolated survival of the population through geological history. Now the species may be threatened by habitat loss. The males of this species are typically 56 mm in length.", region_id: 6, country: "France", animalClass: "Fish", image: "https://s2r.iucnredlist.org/sis2_images/312662276.jpg")

Animal.create(name: "Sinai Agama", sciName: "Pseudotrapelus sinaitus", description: "The length of the lizard including its long slender tail is 18 cm (7 in), the tail accounting for up to two-thirds of its total length. The limbs and tail are long and thin and allow for good climbing and running capability. Pseudotrapelus sinaitus is active during daytime and feeds on insects and other arthropods and plants. During the breeding season, males become a striking blue colour to attract females. The female has brownish-red spots on her sides.", region_id: 7, country: "Libya, Egypt, Palestine, Jordan, Syria, Saudi Arabia, United Arab Emirates, Oman, Sudan, Ethiopia, Eritrea, Djibouti", animalClass: "Reptile", image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/AgamaSinaita01_ST_10_edit.jpg")

Animal.create(name: "Black Seabream", sciName: "Spondyliosoma cantharus", description: "The black seabream is a species of Sparidae fishes. They are recognisable by their oval compressed body and jaws containing 4-6 rows of slender teeth which are larger at the front. They are silvery in colour with blue and pink tinges and broken longitudinal gold lines. They can reach a maximum size of 60 cm in length. They live in northern Europe and in the Mediterranean, usually found on the inshore shelf at depths varying from 5 to 300 m. They are usually found in schools feeding on seaweeds and invertebrates. They breed in February to May leaving eggs in the demersal zone. Black seabream are protogynous meaning females have the ability to change to males.", region_id: 7, country: "Europe, Middle East", animalClass: "Fish", image: "https://www.worldlifeexpectancy.com/images/a/w/b/spondyliosoma-cantharus/spondyliosoma-cantharus.jpg")

Animal.create(name: "Lappet-Faced Vulture", sciName: "Torgos tracheliotos", description: "The lappet-faced vulture is blackish above with a strongly contrasting white thigh feathers. The black feathers on the back of African vultures are lined with brown, while Arabian birds are dark brown rather than black above. The underside can range from pure white to buff-brown. Like many vultures, it has a bald head. The head coloration can range from reddish in southern Africa to dull pink in more northern Africa to pink on the back of the head and gray on the front in the Arabian Peninsula. The combination of the colorful head and fleshy folds on the side of it are distinctive. The bald head of the lappet-faced vulture is advantageous, because a feathered head would become spattered with blood and other fluids, and thus be difficult to keep clean. While flying, lappet-faced vultures have large, broad wings held with the front edges held parallel and slightly pointed, serrated-looking wingtips. Compared to the somewhat similarly marked hooded vulture, it is considerably larger with a more massive bill and can only be confused at a great distance.", region_id: 7, country: "Yemen, Oman, United Arab Emirates, Angola, Namibia, Botswana", animalClass: "Bird", image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/2012-lappet-faced-vulture.jpg")

Animal.create(name: "Striped Hyena", sciName: "Hyaena hyaena", description: "The striped hyena s listed by the IUCN as near-threatened, as the global population is estimated to be under 10,000 mature individuals which continues to experience deliberate and incidental persecution along with a decrease in its prey base such that it may come close to meeting a continuing decline of 10% over the next three generations. It is the smallest of the true hyenas and retains many primitive viverrid characteristics lost in larger species, having a smaller and less specialised skull. Though primarily a scavenger, large specimens have been known to kill their own prey, and attacks on humans have occurred on rare instances. The striped hyena is a monogamous animal, with both males and females assisting one another in raising their cubs. A nocturnal animal, the striped hyena typically only emerges in complete darkness, and is quick to return to its lair before sunrise. Although it has a habit of feigning death when attacked, it has been known to stand its ground against larger predators in disputes over food.", region_id: 7, country: "Middle East, North and East Africa, Central Asia", animalClass: "Mammal", image: "https://upload.wikimedia.org/wikipedia/commons/8/84/Iena_Striata.JPG")

Animal.create(name: "Hyla savignyi", sciName: "Hyla savignyi", description: "Hyla savignyi, also known as the Savigny's treefrog, lemon-yellow tree frog, and Middle East tree frog, is a species of frog in the family Hylidae. The species is endemic to the Middle East including Israel, where it has been declared an endangered species.", region_id: 7, country: "Armenia, Azerbaijan, Cyprus, Egypt, Georgia, Iran, Iraq, Israel, Jordan, Lebanon, Saudi Arabia, Syria, Turkey, Yemen", animalClass: "Amphibian", image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Beqik%C3%AA_H%C3%AA%C5%9F%C3%AEn.jpg")

Animal.create(name: "Moth Skink", sciName: "Lipinia noctua", description: "The moth skink (Lipinia noctua) is a species of skink. It is found in Pacific regions including Sulawesi, Northern Papua New Guinea, Solomon Islands, Vanuatu, Tuamotu, Marquesas Islands, Pitcairn Islands, Hawaii, Indonesia, Fiji, Western Samoa, Admiralty Islands, Bismarck Archipelago, Tonga, Toga, Tegua, Cook Islands and Guam", region_id: 8, country: "Sulawesi, Papua New Guinea, Solomon Islands, Vanatu, Tuamotu, Marquesas Islands, Pitcairn Islands, Hawaii, Indonesia, Fiji, Samoa", animalClass: "Reptile", image: "https://www.ecologyasia.com/images-mno/moth-skink_3133.jpg")

Animal.create(name: "Eel-Tailed Catfish", sciName: "Tandanus tandanus", description: "This fish is also known as dewfish, freshwater catfish, jewfish, and tandan. Eel-tailed catfish have large head with thick and fleshy lips and tubular nostrils. The skin is tough and smooth. Body coloration in adults vary from olive-green to brown, black or purplish on their backs and white on the underside. A downturned mouth with fleshy lips surrounded by a number of barbels assist them with feeding. They are a solid, almost cylindrical, elongate fish, with the posterior half of their body tapering into a pointed eel-like tail. A continuous fin margin surrounds this tapering posterior half of the body. Their eyes are small. The eel-tail catfish has 4 pairs of barbels surrounding the mouth, and sharp serrated dorsal- and pectoral-fin spines which are venomous and can cause a very painful wound.", region_id: 8, country: "Australia", animalClass: "Fish", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Tandanus_tandanus.JPG/220px-Tandanus_tandanus.JPG")

Animal.create(name: "Mariana Crow", sciName: "Corvus kubaryi", description: "The Mariana crow is a glossy black bird about 15 inches (38 cm) long and known only from the islands of Guam and Rota. It is a rare bird which has steadily declined in numbers since the 1960s. On Guam there are believed to be very few remaining birds, the population having been much reduced since the introduction of the brown tree snake. The Mariana crow is a small black crow with a bluish-black gloss on its tail, and a greenish-black gloss on its back, underparts, head, and wings. In general, females are smaller than males. The Mariana crow has a variety of vocalizations, including two locational calls used to maintain contact between pairs, family members and flock mates. These locational calls are either a high-pitched series of one to three caw or hi sounds, or a series of longer caw sounds with a nasal aaa element to the call; the latter call may be used exclusively between mated pairs. Alarm calls are a rapid series of sharp caws. The birds also make a variety of squalling, guttural sounds, which may be done either quietly or excitedly. These sounds are typically accompanied by activities such as the ripping of leaves or the hammering of branches, and may serve as part of courtship or pair bonding.", region_id: 8, country: "Guam, Rota", animalClass: "Bird", image: "http://depts.washington.edu/rabep/Index.2.jpg")

Animal.create(name: "Minke Whale", sciName: "Name not found", description: "The minke whale, or lesser rorqual, is a species complex of baleen whale. The two species of minke whale are the common (or northern) minke whale and the Antarctic (or southern) minke whale. The minke whale is a black/gray/purple color. Common minke whales (Northern Hemisphere variety) are distinguished from other whales by a white band on each flipper. The body is usually black or dark-gray above and white underneath. Minke whales have between 240 and 360 baleen plates on each side of their mouths. Most of the length of the back, including dorsal fin and blowholes, appears at once when the whale surfaces to breathe. Minke whales typically live for 30–50 years; in some cases they may live for up to 60 years. Minke whales have a digestive system composed of four compartments with a high density of anaerobic bacteria throughout. The presence of the bacteria suggests minke whales rely on microbial digestion to extract nutrients provided by their food.", region_id: 8, country: "North Atlantic, North Pacific, Antarctic", animalClass: "Mammal", image: "http://r.ddmcdn.com/s_f/o_1/APL/uploads/2014/10/minke-whale.jpg")

Animal.create(name: "Pseudophryne", sciName: "Pseudophryne", description: "Pseudophryne is a genus of small myobatrachid frogs. All of these frogs are small terrestrial frogs, and as such, most species are commonly called toadlets (pseudo- meaning deceptive, phryne meaning toad). The genus comprises thirteen species, ten from eastern Australia, and three from Western Australia. Species within the genus Pseudophryne lay their eggs on moist ground. The tadpoles develop within the eggs, and once they reach hatching size, will become dormant. Once sufficient rain occurs to flush the eggs into a creek or river, the eggs will hatch and release tadpoles into the water. Many of the species within this genus have the ability to form hybrids.", region_id: 8, country: "Australia", animalClass: "Amphibian", image: "https://s2r.iucnredlist.org/sis2_images/633530878.jpg")

Animal.create(name: "Jamaican Iguana", sciName: "Cyclura collei", description: "The species is endemic to Jamaica. It is the largest native land animal in Jamaica, and is critically endangered, even considered extinct between 1948 and 1990. Once found throughout Jamaica and on the offshore islets Great Goat Island and Little Goat Island, it is now confined to the forests of the Hellshire Hills. The Jamaican iguana is a large heavy-bodied lizard primarily green to salty blue in color with darker olive-green coloration on the shoulders. Three dark broad chevrons extend from the base of the neck to the tail on the animal's back, with dark olive-brown zigzag spots. The dorsal crest scales are somewhat brighter bluish-green than the body. The body surfaces are blotched with a yellowish blotched color breaking up into small groups of spots.", region_id: 9, country: "Jamaica", animalClass: "Reptile", image: "https://upload.wikimedia.org/wikipedia/commons/0/06/Jamaican_iguana_on_tree.jpg")

Animal.create(name: "Atlantic Goliath Grouper", sciName: "Epinephelus itajara", description: "The Atlantic goliath grouper is a large saltwater fish of the grouper family found primarily in shallow tropical waters among coral and artificial reefs at depths from 5 to 50 m (16 to 164 ft). Young Atlantic goliath grouper may live in brackish estuaries, oyster beds, canals, and mangrove swamps, which is unusual behavior among groupers. They may reach extremely large sizes, growing to lengths up to 2.5 m (8.2 ft) and can weigh as much as 360 kg (790 lb). The world record for a hook-and-line-captured specimen is 308.44 kg (680.0 lb), caught off Fernandina Beach, Florida, in 1961. The fish is entirely protected from harvest and is recognized as a Vulnerable species by the IUCN. The US began protection in 1990, and the Caribbean in 1993. The species' population has been recovering since the ban; with the fish's slow growth rate, however, some time will be needed for populations to return to their previous levels.", region_id: 9, country: "Atlantic Ocean", animalClass: "Fish", image: "https://mission-blue.org/wp-content/uploads/2017/06/14361311_1831279333772390_160683212407351940_o.jpg")

Animal.create(name: "Cuban Amazon", sciName: "Amazona leucocephala", description: "he Cuban amazon also known as Cuban parrot or the rose-throated parrot, is a medium-sized mainly green parrot found in woodlands and dry forests of Cuba, the Bahamas and Cayman Islands in the Caribbean. The Cuban amazon is a medium-sized parrot 28–33 centimetres (11–13 in) long. It is mainly green with some blue feathers in its wings. The green feathers are edged with a terminal black rim. Its lower face, chin and throat are rosy pink, and its forehead and eye-rings are white. The extent of the various colours of the head, the extent of the rosy pink on the upper chest, and the extent of the dull red on the abdomen vary between the subspecies. Its irises are pale olive-green, its beak is horn-coloured, and the feathers over the ears are blackish. The legs are pink. The juvenile has little or no red on the abdomen, less black edging on the green feathers, and some of the feathers on the top of its head may be pale yellow rather than white.", region_id: 9, country: "Cuba", animalClass: "Bird", image: "http://animalia.bio/uploads/animals/photos/full/1.25x1/cuban-parrot-amazona-leucocephala-2.jpg")

Animal.create(name: "West Indian Manatee", sciName: "Trichechus manatus", description: 'The West Indian manatee or "sea cow", also known as North American manatee, is the largest surviving member of the aquatic mammal order Sirenia.On March 30, 2017, the US Secretary of the Interior Ryan Zinke announced the federal reclassification of the manatee from endangered to threatened as the number of sea cows had increased to over 6,000. Since manatees are mammals, they breathe air, have warm blood, have hair, and give birth to live young. Like the other sirenians, the West Indian manatee has adapted fully to aquatic life, having no hind limbs. Instead of hind limbs, the manatee has a spatula-like paddle for propulsion in the water. Manatees have evolved streamlined bodies which lack external ear flaps, thus decreasing resistance in the aquatic environment. Pelage cover is sparsely distributed across the body, which may play a role in reducing the build-up of algae on their thick skin. Manatee skin is gray but can vary in coloration due to algae and other biota, like barnacles, that opportunistically live on manatees. Scar tissue on manatees is white and persists for decades, allowing for easy identification. The Florida manatee has three to four nails on each flipper. Nails are absent in the Amazonian manatee.', region_id: 9, country: "Caribbean", animalClass: "Mammal", image: "https://www.fws.gov/southeast/images/hero/manatee-cow-and-calf.jpg")

Animal.create(name: "Cuban Tree Frog", sciName: "Osteopilus septentrionalis", description: "The Cuban tree frog is the largest tree frog of North America. Its wide diet and ability to thrive amongst humans has made it a highly invasive species with established colonies throughout peninsular Florida, the Hawaiian island of Oahu, and throughout the Caribbean Islands. They range in size from 3 to 5.5 in (76 to 140 mm) and vary in color from olive-brown and bronze to gray or grayish-white. A nocturnal, tree-dwelling frog, it is known to eat almost anything that will fit in its mouth and to mate year-round. Cuban tree frogs are commonly available as pets; however, because the animal secretes a toxic mucus from its skin that can cause a burning sensation in the eyes, it is not an ideal pet. Further distribution of the species is believed to have been expanded by the release of these pet animals.", region_id: 9, country: "Caribbean", animalClass: "Amphibian", image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Osteopilus_septentrionalis_6.jpg")

User.create(name: "Aliya", username: "liya", password: "123")
User.create(name: "Aliya", username: "aaliyah", password: "123")

# Animal.create(name: "", sciName: "", description: "", region_id: , country: "", animalClass: "", image: "")
